# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         HTML-MobileConverter
version:      0.01
version_from: lib/HTML/MobileConverter.pm
installdirs:  site
requires:
    HTML::Parser:                  3.45
    URI:                           1.33

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
